# Generated by Django 6.1.1 on 2026-09-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha_j1', models.CharField(blank=True, max_length=10, null=True)),
                ('escolha_j2', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='aguardando_oponente', max_length=30)),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_j1', to=settings.AUTH_USER_MODEL)),
                ('jogador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos_como_j2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
